"""
Email Sender — Sends the analysis report via Gmail SMTP with the DOCX attached.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

from config import get_smtp_credentials, SMTP_HOST, SMTP_PORT


def send_report_email(
    to_email: str,
    company_name: str,
    report_path: str,
    analysis_summary: str = "",
    recommendation: str = "",
) -> tuple[bool, str]:
    """
    Send the financial analysis report as an email attachment.

    Returns:
        (True, "")              on success
        (False, error_str)      on failure
    """
    # ── Resolve credentials ──────────────────────────────────────────────────
    try:
        smtp_email, smtp_password = get_smtp_credentials()
    except RuntimeError as cred_err:
        print(f"  ❌ SMTP not configured: {cred_err}")
        return False, str(cred_err)

    # ── Build email ──────────────────────────────────────────────────────────
    msg = MIMEMultipart()
    msg["From"] = smtp_email
    msg["To"] = to_email
    msg["Subject"] = f"📊 Financial Analysis Report — {company_name}"

    # Email body (HTML)
    body_html = f"""
    <html>
    <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">

            <!-- Header -->
            <div style="background: linear-gradient(135deg, #1A254B, #2E86C1); padding: 30px; text-align: center;">
                <h1 style="color: white; margin: 0; font-size: 24px;">📊 Financial Analysis Report</h1>
                <p style="color: #B0C4DE; margin: 10px 0 0 0; font-size: 16px;">{company_name}</p>
            </div>

            <!-- Body -->
            <div style="padding: 30px;">
                <p style="font-size: 15px; line-height: 1.6;">Hello,</p>

                <p style="font-size: 15px; line-height: 1.6;">
                    Please find attached the comprehensive financial analysis report for
                    <strong>{company_name}</strong>.
                </p>

                {f'''
                <div style="background: #f8f9fa; border-left: 4px solid #2E86C1; padding: 15px; margin: 20px 0; border-radius: 4px;">
                    <strong>Executive Summary:</strong><br>
                    <span style="font-size: 14px; color: #555;">{analysis_summary}</span>
                </div>
                ''' if analysis_summary else ''}

                {f'''
                <div style="text-align: center; margin: 25px 0;">
                    <span style="
                        display: inline-block;
                        padding: 10px 30px;
                        border-radius: 6px;
                        font-size: 18px;
                        font-weight: bold;
                        color: white;
                        background: {"#27AE60" if recommendation.upper() == "BUY" else "#C0392B" if recommendation.upper() in ("SELL", "AVOID") else "#E67E22"};
                    ">
                        Recommendation: {recommendation}
                    </span>
                </div>
                ''' if recommendation else ''}

                <p style="font-size: 15px; line-height: 1.6;">
                    The report includes:
                </p>
                <ul style="font-size: 14px; line-height: 1.8; color: #555;">
                    <li>Company Background & Research</li>
                    <li>Competitor Analysis</li>
                    <li>Financial Statement Analysis</li>
                    <li>Financial Ratios (Liquidity, Profitability, R' Ratios, Solvency, Efficiency)</li>
                    <li>Risk Factors & Investment Pros</li>
                    <li>Investment Recommendation</li>
                </ul>

                <p style="font-size: 13px; color: #999; margin-top: 30px; font-style: italic;">
                    <em>Disclaimer: This is an AI-generated analysis for informational purposes only.
                    It does not constitute financial advice. Please consult a qualified financial advisor
                    before making investment decisions.</em>
                </p>
            </div>

            <!-- Footer -->
            <div style="background: #f8f9fa; padding: 15px; text-align: center; border-top: 1px solid #e0e0e0;">
                <p style="font-size: 12px; color: #999; margin: 0;">
                    Generated by Financial Statement Analyzer • Automated Analysis Tool
                </p>
            </div>
        </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(body_html, "html"))

    # ── Attach DOCX (optional — send without if file is missing) ─────────────
    if report_path and os.path.exists(report_path):
        with open(report_path, "rb") as f:
            attachment = MIMEBase("application", "octet-stream")
            attachment.set_payload(f.read())
            encoders.encode_base64(attachment)
            attachment.add_header(
                "Content-Disposition",
                f'attachment; filename="{os.path.basename(report_path)}"',
            )
            msg.attach(attachment)
    else:
        print(f"  ⚠️  Report file not found at '{report_path}' — sending email without DOCX attachment")

    # ── Send ──────────────────────────────────────────────────────────────────
    import socket
    orig_getaddrinfo = socket.getaddrinfo
    def getaddrinfo_ipv4(host, port, family=0, type=0, proto=0, flags=0):
        res = orig_getaddrinfo(host, port, family, type, proto, flags)
        ipv4_res = [r for r in res if r[0] == socket.AF_INET]
        return ipv4_res if ipv4_res else res

    socket.getaddrinfo = getaddrinfo_ipv4
    try:
        print(f"  📧 Connecting to {SMTP_HOST}:{SMTP_PORT} as {smtp_email}...")
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_email, smtp_password)
            server.send_message(msg)

        print(f"  ✅ Email sent successfully to {to_email}")
        return True, ""

    except smtplib.SMTPAuthenticationError as e:
        reason = "SMTP authentication failed. Check SMTP_EMAIL and SMTP_APP_PASSWORD in Railway Variables."
        print(f"  ❌ {reason} ({e})")
        return False, reason
    except smtplib.SMTPException as e:
        reason = f"SMTP error: {e}"
        print(f"  ❌ {reason}")
        return False, reason
    except Exception as e:
        reason = f"Email send failed: {e}"
        print(f"  ❌ {reason}")
        return False, reason
    finally:
        socket.getaddrinfo = orig_getaddrinfo
